### ISSUE TITLE
pbicop returning values > 1

### ISSUE THREAD

**Issue by ivanlongin** [vinecopulib/rvinecopulib#117]
In R:

u = matrix(c(0.5215358, 0.5762758,
0.1901277, 0.6213009,
0.6106837, 0.8506270,
0.2900435, 0.3769789,
0.3729131, 0.4309416,
0.6349203, 0.6944853), ncol = 2, byrow = TRUE)

pbicop(u, family='t', rotation = 0, parameters = c(0.920266, 6.295919))

[1] 0.8205036 0.3230017 1.0363803 0.4517086 0.5717643 1.0253078

**Comment by tvatter** [comment]
Hi @ivanlongin,

The issue was related to non-integer degrees of freedom.

The fix will be part of the next release that we are preparing (most likely beginning of next week on CRAN).

If you want to use it already, I pushed the fix in the weights branch that contain all of the new features and bug fixes. You can install it via `devtools::install_github("vinecopulib/rvinecopulib", ref = "weights")`.

Note that, if you want to install this new version, you'll need the latest versions of the [RcppThread](https://cran.r-project.org/web/packages/RcppThread/index.html) and [wdm](https://cran.r-project.org/web/packages/wdm/index.html) packages that Thomas pushed to CRAN yesterday. Furthermore, it seems that the binary of the two packages are not yet available, so you will need to do `install.packages("RcppThread", type = "source")` and  `install.packages("wdm", type = "source")` before you can do `devtools::install_github("vinecopulib/rvinecopulib", ref = "weights")`.

Notice of caution, we made several modifications that considerably slowed down the compilation time for rvinecopulib. Don't worry if it takes a while to install, we are still working on it.

**Comment by tvatter** [comment]
u = matrix(c(0.5215358, 0.5762758,
0.1901277, 0.6213009,
0.6106837, 0.8506270,
0.2900435, 0.3769789,
0.3729131, 0.4309416,
0.6349203, 0.6944853), ncol = 2, byrow = TRUE)

pbicop(u, family='t', rotation = 0, parameters = c(0.920266, 6.295919))

[1] 0.4814888 0.1895326 0.6081557 0.2650689 0.3355233 0.6016786
