### ISSUE TITLE
Compilation time

### ISSUE THREAD

**Issue by tvatter** [vinecopulib/rvinecopulib#122]
Vinecopulib is growing, and so does its compilation time. Furthermore, since it is header-only and rvinecopulib includes the library via three xyz_wrappers.cpp files, building rvinecopulib means compiling vinecopulib three times.

I see three solutions:

1. Importing the non-header only version.
2. Using a single wrapper file.
3. Being "more careful" when including headers of vinecopulib in the wrappers (i.e., including only what's necessary rather than the full library).

1 and 2 are equivalent in term of raw performance. In terms of drawbacks: 1 would imply that other packages can't use LinkingTo (is it true though? if we just move the cpp files in src via the script and keep the headers as they are now?), while 2 would amount at using a large big messy file.

Now 3 is a way of keeping the header-only while being a bit cleaner than 2. However, we'll still build parts of vinecopulib several times.

Any thoughts?

**Comment by tnagler** [comment]
Generally, I don't think there's huge potential for speedup. Most of the slowness (at least for me) came with all these freaking compiler warnings from RcppEigen and BH. Now to the solutions:

1. We should definitely allow for `LinkingTo`.
2. That's an option.
3. Don't think we can do much here. Things that aren't used shouldn't be compiled anyway afaik.

How about putting the header only version in `inst/include`, but putting the shared lib headers in `src/include/`, the cpps in `src/` and building the shared lib from there? We can't use the headers of `inst/include` ourselves though, because then we would define functions multiple times.

**Comment by tvatter** [comment]
1. I'm not convinced. It's a pretty specific (as opposed to general purpose) library.
3. For instance, we don't need to include the vine headers in the bicop wrappers, but if you're right about the not used/not compiled, it does not matter indeed.

**Comment by tnagler** [comment]
1. Yeah, but stuff like vinereg I would have written in C++ with a LinkingTo if that option would have existed back then. And at least I intend to do similar things that way in the future. If one cannot use the headers via LinkinTo, one always has to include all vinecopulib headers as part of any other package.

**Comment by tvatter** [comment]
1. Yeah, vinereg and eecop are examples that comes to mind, but even us didn't link again the vinecopulib headers ;) Also, are you sure that we can't link against the functions in vinecopulib if the headers are in inst and the library is compiled in a "standard" way ?

**Comment by tnagler** [comment]
1. Apparently there is no other way when using custom C++ classes. 
2. Using a single wrapper file brought down compilation time from ~1m45s to ~45s on my machine (single core). I think that's reasonable, so I would vote for this option.

**Comment by tvatter** [comment]
See #124
