### ISSUE TITLE
fitting "indep" instead of "tll" for hashed data

### ISSUE THREAD

**Issue by tagas** [vinecopulib/rvinecopulib#157]
Hi,

I have a strange issue when I try to fit a nonparametric copula with mult=0.1, it actually fits an "indep" copula. I'm attaching a script and data to reproduce the issue.  

[git_issue.zip](https://github.com/vinecopulib/rvinecopulib/files/2611204/git_issue.zip)

**Comment by tnagler** [comment]
Hey, thanks for the issue. The indep copula thing should be fixed in this branch: https://github.com/vinecopulib/rvinecopulib/tree/fix-bicop-select. 

However, it appears that the margin fits are terrible anyway:
``` r
hist(kde1d::pkde1d(real_traj_data[, 1], vine_obj$margins[[1]]))
```
This should resemble a uniform distribution, but is far from it. I'll look into that as well.

**Comment by tnagler** [comment]
OK, the marginal distributions just seem to be super weird and cannot be approximated better using the interpolation approach in kde1d. I may work on this some time in the near future, but that will take time. In the meanwhile, you could fit the margins separately, use `pseudo_obs()`, and then fit the vine. This should make it more stable.
